import { Dispatcher, StoreRegistry } from 'ap-flux';

/* This class was auto-generated by the JavaScriptWriter */
class AppHelper {

	register(path, obj, callback) {
		StoreRegistry.register('APP_STORE' + (path ? path : '') , obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('APP_STORE', obj);
	}

	getData(path) {
		return StoreRegistry.getStore('APP_STORE').getData(path);
	}

	navigate(path) {
		return Dispatcher.issue('NAVIGATE', { path: path });
	}

	navigateBack() {
		return Dispatcher.issue('NAVIGATE_BACK', {});
	}

	setBusy(busy) {
		return Dispatcher.issue('SET_APP_DISPLAY', { path: '/busy', value: !!busy });
	}

}
var AppHelperObj = new AppHelper();
export default AppHelperObj;
