import AppHelper from 'helpers/AppHelper';

/* This class was auto-generated by the JavaScriptWriter */
class AppData {

	register(callback) {
		this.callback = callback
		this.onStoreUpdate()
	}

	onStoreUpdate() {
		this.buildData()
		this.callback()
	}

	unregister() {
	}

	buildData() {
	}

}
var AppObj = new AppData();
export default AppObj;
