import TextUtils from 'utils/TextUtils'

export default class Nationnalities {

	static get VALUES() { return [		
		"afghane",
		"albanaise",
		"algérienne",
		"allemande",
		"américaine",
		"andorrane",
		"angolaise",
		"argentine",
		"arménienne",
		"australienne",
		"autrichienne",
		"azerbaïdjanaise",
		"bahamienne",
		"bahreïnienne",
		"bangladaise",
		"barbadienne",
		"bélarussienne",
		"belge",
		"bélizienne",
		"béninoise",
		"bhoutanaise",
		"bolivienne",
		"botswanaise",
		"brésilienne",
		"britannique",
		"bulgare",
		"burkinabè",
		"burundaise",
		"cambodgienne",
		"camerounaise",
		"canadienne",
		"cap-verdienne",
		"centrafricaine",
		"chilienne",
		"chinoise",
		"chypriote",
		"colombienne",
		"comorienne",
		"congolaise",
		"costaricienne",
		"croate",
		"cubaine",
		"d'Antigua-et-Barbuda",
		"danoise",
		"de Bosnie-et-Herzégovine",
		"de Guinée-Bissau",
		"de l'ancienne République yougoslave de Macédoine",
		"de la République de Chine, de Taïwan",
		"de Papouasie - Nouvelle-Guinée",
		"de Saint-Christophe-et-Nevis",
		"de Saint-Vincent-et-les-Grenadines",
		"de São Tomé e Príncipe",
		"de Sierra Leone",
		"des Émirats arabes unis",
		"des Îles Fidji",
		"djiboutienne",
		"dominicaine",
		"dominiquaise",
		"du Brunei",
		"du Lesotho",
		"du Myanmar",
		"du Saint-Siège",
		"égyptienne",
		"équato-guinéenne",
		"équatorienne",
		"érythréenne",
		"espagnole",
		"est-timorais",
		"estonienne",
		"éthiopienne",
		"finlandaise",
		"française",
		"gabonaise",
		"gambienne",
		"géorgienne",
		"ghanéenne",
		"grecque",
		"grenadine",
		"guatémaltèque",
		"guinéenne",
		"guyanienne",
		"haïtienne",
		"hondurienne",
		"hongroise",
		"indienne",
		"indonésienne",
		"iranienne",
		"iraquienne",
		"irlandaise",
		"islandaise",
		"israélienne",
		"italienne",
		"ivoirienne",
		"jamaïquaine",
		"japonaise",
		"jordanienne",
		"kazakhe",
		"kényane",
		"kirghize",
		"kiribatienne",
		"koweïtienne",
		"laotienne",
		"lettone",
		"libanaise",
		"libérienne",
		"libyenne",
		"liechtensteinoise",
		"lituanienne",
		"luxembourgeoise",
		"malaisienne",
		"malawienne",
		"maldivienne",
		"malgache",
		"malienne",
		"maltaise",
		"marocaine",
		"marshallaise",
		"mauricienne",
		"mauritanienne",
		"mexicaine",
		"micronésienne",
		"moldove",
		"monégasque",
		"mongole",
		"mozambicaine",
		"namibienne",
		"nauruane",
		"néerlandaise",
		"néo-zélandaise",
		"népalaise",
		"nicaraguayenne",
		"nigériane",
		"nigérienne",
		"nord-coréenne",
		"norvégienne",
		"omanaise",
		"ougandaise",
		"ouzbèke",
		"pakistanaise",
		"palauane",
		"panaméenne",
		"paraguayenne",
		"péruvienne",
		"philippine",
		"polonaise",
		"portugaise",
		"qatarienne",
		"roumaine",
		"russe",
		"rwandaise",
		"saint-lucienne",
		"saint-marinaise",
		"salomonaise",
		"salvadorienne",
		"samoane",
		"saoudienne",
		"sénégalaise",
		"seychelloise",
		"singapourienne",
		"slovaque",
		"slovène",
		"somalienne",
		"soudanaise",
		"sri-lankaise",
		"sud-africaine",
		"sud-coréenne",
		"suédoise",
		"suisse",
		"surinamaise",
		"swazie",
		"syrienne",
		"tadjike",
		"tanzanienne",
		"tchadienne",
		"tchèque",
		"thaïlandaise",
		"togolaise",
		"tongane",
		"trinidadienne",
		"tunisienne",
		"turkmène",
		"turque",
		"tuvaluane",
		"ukrainienne",
		"uruguayenne",
		"vanuatuane",
		"vénézuélienne",
		"vietnamienne",
		"yéménite",
		"yougoslave",
		"zambienne",
		"zimbabwéenne"
	].map(function(value) { 
		return TextUtils.capitalize(value) 
	} )}
}